schemaVersion: 1.0.0
name: Waffler Developer CLI
vision: Core vision for Waffler Developer CLI
boundaries: []
globalRequirements: []
databases: []
createdAt: '2026-09-09T23:09:59.437Z'
updatedAt: '2026-09-09T23:09:59.437Z'
